name: Tag main when PRs/Push Actions Come from release Branches
on:
  push:
    branches: [ "main" ]

jobs:
  if-pr-not-from-release-branch:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Log Message if PR was not merged from the release Branch
        run: |
          echo "PR merged from non release branch -> ${{ github.event.head_commit.message }} - exiting"

      - name: Exit with Error if PR was not merged from the release Branch
        if: steps.get-repo-branch-match.outputs.match == ''
        run:
          exit 1

  if-pr-from-release-branch:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      # get pr branch name
      - name: Get PR Branch Name
        run: |
          echo "PR Branch Name: ${{ github.event.pull_request.head.ref }}"
      - name: Get Repo Branch Match
#        uses: actions-ecosystem/action-regex-match@9e6c4fb3d5e898f505be7a1fb6e7b0a278f6665b # v2.0.2
#        id: get-repo-branch-match
#        with:
#          text: ${{ github.event.head_commit.message }}
#          regex: '\bmol-george\/release\/\d\.\d\.\d\b'
#
#      - name: Log message if Head Commit Repo and Branch Names do not match expected regex
#        if: steps.get-repo-branch-match.outputs.match == ''
#        run:
#          echo "The Github Head Commit Message which is expected to contain the name of repo and branch from which the PR was submitted did not returned a match for 'mol-george/release/xx.xx.xx'. Check the Github Head Commit Message -> ${{ github.event.head_commit.message }} - exiting"

#      - name: Exit with Error if Head Commit Repo and Branch Names do not match Expected REGEX
#        if: steps.get-repo-branch-match.outputs.match == ''
#        run:
#          exit 1
#
#      - name: Get Release Branch Major.Minor.Patch Number
#        uses: actions-ecosystem/action-regex-match@9e6c4fb3d5e898f505be7a1fb6e7b0a278f6665b # v2.0.2
#        id: get-release-branch-major-minor-patch-number
#        with:
#          text: ${{ github.event.head_commit.message }}
#          regex: '\b\d\.\d\.\d\b'
#
#      - name: Checking out Repo
#        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
#
#      # TEST: pushing from release branch
#      - name: Tag Main Branch with the PR's Commit
#        uses: rickstaa/action-create-tag@1ef0869561b8f45faba8b8e29984eb83b054e242 # v1.3.2
#        with:
#          tag: "${{ steps.get-release-branch-major-minor-patch-number.outputs.match }}"
#          force_push_tag: true
#          message: "main branch tagged with the major.minor.patch version of the release branch pointing to the PR's commit"