name: Print Info About PRs
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  if-pr-from-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info
        run: echo ${{ pull_request.head.ref }}