name: Tag Main
on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  tag-main:
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Get Release MMP
        id: get-release-mmp
        uses: JungWinter/split@0f0d1192ba8045bc5e85a341074fc210ef9da69e # v2
        with:
          msg: ${{ github.event.pull_request.head.ref }}
          separator: "/"

      - name: Print Info
        run: echo ${{ steps.get-release-mmp.outputs._1 }}

      - name: Checking out Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Tag Main Branch with the PR's Commit
        uses: rickstaa/action-create-tag@1ef0869561b8f45faba8b8e29984eb83b054e242 # v1.3.2
        with:
          tag: "${{ steps.get-release-mmp.outputs._1 }}"
          force_push_tag: true
          message: "main branch tagged with the major.minor.patch version of the release branch pointing to the PR's commit"