name: Tag main when PRs/Push Actions Come from release Branches
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  if-pr-from-release-branch:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Print Info
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.event.pull_request }}