name: Print Info About PRs
on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  tag-main:
    if: startsWith(github.event.pull_request.head.ref, 'release')
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Print Info
        run: |
          echo ${PR_BRANCH}