name: Print Info About PRs
on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  tag-main:
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Get Release MMP
        id: get-release-mmp
        uses: jungwinter/split@v2
        with:
          msg: ${{ github.event.pull_request.head.ref }}
          separator: "/"
      - name: Print Info
        run: |
          echo "PR_BRANCH: ${PR_BRANCH}"
          echo ${{ steps.get-release-mmp._1 }}