name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Is Push Coming From release/xx.xx.xx branch
        id: is-push-from-release-branch
        env:
          GITHUB_CONTEXT: ${{ github.event.head_commit.message }}
        run: echo $GITHUB_CONTEXT