name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  if-pr-not-from-release-branch:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Log Message
        run: |
          echo "Head Commit Message -> ${{ github.event.head_commit.message }}"
          echo "PR does not come from a release branch - exiting"

  if-pr-from-release-branch:
    # Job to Run if PR comes from a release branch
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      # Print github.event.head.ref to console
      - name: print-github-event
        run: echo "${{ github.event}}"
#      ## Get the Head Commit Branch Name
#      - name: Get Head Commit Branch Name
#        uses: actions-ecosystem/action-regex-match@v2
#        id: get-head-commit-branch-name
#        with:
#          text: ${{ github.event.head_commit.message }}
#          regex: 'release\/\d\.\d\.\d'
#      # If steps.get-head-commit-branch-name.outputs.match is null exit the workflow
#      - name: Check if Head Commit Branch Name is Null
#        if: ${{ steps.get-head-commit-branch-name.outputs.match }} == null
#        run: |
#          echo "Head Commit Branch Name is Null - exiting"
#          exit 1
#      - name: Print Head Commit Branch Name
#        run: echo ${{ steps.get-head-commit-branch-name.outputs.match}}