name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Log Message and Exit
        run: echo "PR does not come from a release branch - exiting"

  two:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Head Commit Message
        env:
          GITHUB_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo ${GITHUB_HEAD_COMMIT_MESSAGE}