name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  github-event-head-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Log Messages
        run: |
          echo "github-event          -> ${{ github.event }}"
          echo "github-event-head-ref -> ${{ github.event.head.ref }}"
