name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  if-pr-not-from-release-branch:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Log Message
        run: |
          echo "Head Commit Message -> ${{ github.event.head_commit.message }}"
          echo "PR does not come from a release branch - exiting"

  if-pr-from-release-branch:
    # Job to Run if PR comes from a release branch
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      ## Get the Head Commit Branch Name
      - name: Get Head Commit Branch Name
        uses: actions-ecosystem/action-regex-match@v2
        id: get-head-commit-branch-name
        env:
          HEAD_COMMIT_BRANCH_NAME: ${{ toJson(github.event.head_commit.message) }}
        with:
          text: ${{ github.event.head_commit.message }}
          regex: 'release\/\d\.\d\.\d'
      # Print steps.get-head-commit-branch-name.outputs.match
      - name: Print Head Commit Branch Name
        run: |
          echo "HEAD_COMMIT_BRANCH_NAME -> ${HEAD_COMMIT_BRANCH_NAME}"
          echo "Head Commit Branch Name -> ${{ steps.get-head-commit-branch-name.outputs.match }}"
      # # If steps.get-head-commit-branch-name.outputs.match is null exit the workflow
      # - name: Check if Head Commit Branch Name is Null
      #   if: ${{ steps.get-head-commit-branch-name.outputs.match }} == null
      #   run: |
      #     echo "Head Commit Branch Name is Null - exiting"
      #     exit 1
      # - name: Print Head Commit Branch Name
      #   run: echo ${{ steps.get-head-commit-branch-name.outputs.match}}