name: twf1
on:
  push:
    branches: [ "main" ]

jobs:
  if-pr-not-from-release-branch:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Log Message
        run: |
          echo "PR merged from non release branch -> ${{ github.event.head_commit.message }} - exiting"

      - name: Exit with Error if PR was not merged from the release Branch
        if: steps.get-repo-branch-match.outputs.match == ''
        run:
          exit 1

  if-pr-from-release-branch:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Get Repo Branch Match
        uses: actions-ecosystem/action-regex-match@v2
        id: get-repo-branch-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '\bmol-george\/release\/\d\.\d\.\d\b'

      - name: Log message if Head Commit Repo and Branch Names do not match expected regex
        if: steps.get-repo-branch-match.outputs.match == ''
        run:
          echo "The Github Head Commit Message which is expected to contain the name of repo and branch from which the PR was submitted did not returned a match for 'mol-george/release/xx.xx.xx'. Check the Github Head Commit Message -> ${{ github.event.head_commit.message }} - exiting"

      - name: Exit with Error if Head Commit Repo and Branch Names do not match Expected REGEX
        if: steps.get-repo-branch-match.outputs.match == ''
        run:
          exit 1

      - name: Get Release Branch Major.Minor.Patch Number
        uses: actions-ecosystem/action-regex-match@v2
        id: get-release-branch-major-minor-patch-number
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '\b\d\.\d\.\d\b'

      - name: Checking out Repo
        uses: actions/checkout@v3

      # Test 3
      - name: Tag Main Branch with the PR's Commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.get-release-branch-major-minor-patch-number.outputs.match }}"
          force_push_tag: true
          message: "main branch tagged with the major.minor.patch version of the release branch pointing to the PR's commit"