name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Echo Head Commit Message
        env:
          GITHUB_HEAD_COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
        run: |
          echo ${GITHUB_HEAD_COMMIT_MESSAGE}
      - name: Log Message
        run: echo "PR does not come from a release branch - exiting"
      # - name: Exit
      #   run: exit 1

  two:
    ### Job to Run if PR comes from a release branch
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Echo Head Commit Message
        run: echo ${{ github.event.head_commit.message }}
      - name: Log Message
        run: echo "PR comes from a release branch - continuing"