name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Is Push Coming From release/xx.xx.xx branch
        uses: sergeysova/jq-action@v2
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          # cmd: "jq .event.head_commit.message <<<${GITHUB_CONTEXT}"
          cmd: echo "${GITHUB_CONTEXT}" | jq '.event.head_commit.message'