name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Is Push Coming From release/xx.xx.xx branch
        # uses: sergeysova/jq-action@v2
        id: is-push-from-release-branch
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_REF
          echo $GITHUB_HEAD_REF
          if [[ $GITHUB_REF =~ ^refs/heads/release/ ]]; then
            echo "true"
          else
            echo "false"
          fi
        # with:
        #   cmd: 'jq . <<<"${GITHUB_CONTEXT}"'
        #   multiline: true
        #   # cmd: echo "${GITHUB_CONTEXT}" | jq -r '.event.head_commit.message'

      # Testing
      - name: Show Commit Head Message
        run: 'echo "is-push-from-release-branch: ${{ steps.is-push-from-release-branch.outputs.value }}"'
