name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  github-event-head-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Log Messages
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "github-event          -> ${GITHUB_EVENT}"
          echo "github-event-head-ref -> ${{ github.event.head.ref }}"
