name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  if-pr-not-from-release-branch:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Log Message
        run: |
          echo "Head Commit Message -> ${{ github.event.head_commit.message }}"
          echo "PR does not come from a release branch - exiting"

  if-pr-from-release-branch:
    # Job to Run if PR comes from a release branch
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - name: Print Head Commit Branch
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '\d\.\d\.\d'
      - name: Log Message
        run: echo ${{ steps.regex-match.outputs.match}}