name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Is Push Coming From release/xx.xx.xx branch
        id: is-push-from-release-branch
        if: echo "PR does not come from a release branch" && !contains( github.event.head_commit.message, 'release' )
