name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  github-event-head-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Log Message
        run: |
          echo "github-event-head-commit-message -> ${{ github.event.head_commit.message }}"
          echo "github-event-head-ref            -> ${{ github.event.head.ref }}"
