name: twf1
on:
  push:
    branches: [ "main" ]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Is Push Coming From release/xx.xx.xx branch
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          if [[ grep -q "release\/\d\.\d\.\d" <<<"${GITHUB_CONTEXT}" ]]; then
            echo "Push is from release/xx.xx.xx branch"
          else
            echo "Push is not from release/xx.xx.xx branch"
            exit 1
          fi